name: Pages
on:
  workflow_dispatch:
  pull_request:
    branches: [effect-native/main]
  push:
    branches: [effect-native/main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: linux
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm docgen
      - name: Build pages Jekyll
        if: github.repository_owner == 'effect-native' && github.event_name == 'push' && github.ref == 'refs/heads/effect-native/main'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload pages artifact
        if: github.repository_owner == 'effect-native' && github.event_name == 'push' && github.ref == 'refs/heads/effect-native/main'
        uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.repository_owner == 'effect-native' && github.event_name == 'push' && github.ref == 'refs/heads/effect-native/main'
    name: Deploy
    runs-on: self-hosted
    timeout-minutes: 10
    needs: build
    permissions:
      pages: write # To deploy to GitHub Pages
      id-token: write # To verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
