name: Release
on:
  push:
    branches: [effect-native/main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    if: github.repository_owner == 'effect-native'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install dependencies
        uses: effect-native/effect-native/.github/actions/setup@6dbea705cc0cbb0aad92e60785a8179bd8555434

      - name: Setup Node for npm Registry
        uses: actions/setup-node@v4
        with:
          node-version: "23.7.0"
          registry-url: "https://registry.npmjs.org"
          scope: "@effect-native"
          cache: pnpm

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba
        with:
          version: pnpm changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish with OIDC
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm changeset-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
