name: Node CI

on:
  push:
    branches:
      - issue/**
      - features/**
      - generic/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install -g lerna
          npm install -g yarn
          lerna bootstrap
          lerna run build
          yarn jest --detectOpenHandles
          lerna run lint --parallel
          lerna run bench
        env:
          CI: "true"

      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
